
# Increase JVM heap to fix OutOfMemoryError
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Performance
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Android
android.useAndroidX=true

# Remove all deprecated flags (deleted):
# android.enableJetifier ? only add back if you use old Support libraries
# android.usesSdkInManifest.disallowed
# android.newDsl
# android.r8.optimizedResourceShrinking
# android.defaults.buildfeatures.resvalues
# android.builtInKotlin
# android.enableAppCompileTimeRClass